sudo: required
services:
  - docker

before_install:
  - docker build -t gustafdahl/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true gustafdahl/react-test npm test

after_success:
  - docker build -t gustafdahl/multi-client ./client
  - docker build -t gustafdahl/multi-nginx ./nginx
  - docker build -t gustafdahl/multi-server ./server
  - docker build -t gustafdahl/multi-worker ./worker

  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gustafdahl/multi-client
  - docker push gustafdahl/multi-nginx
  - docker push gustafdahl/multi-server
  - docker push gustafdahl/multi-worker
